### ISSUE TITLE
Layout Params Exception

### ISSUE THREAD

**Issue by green985** [henryblue/TvRecyclerView#33]
Thank for amazing library but I have to problem with end of recycler view item last index

Or some recycler view make this exception and app crashed. 

Thanks for support

java.lang.ClassCastException: android.support.constraint.ConstraintLayout$LayoutParams cannot be cast to android.support.v7.widget.RecyclerView$LayoutParams
        at android.support.v7.widget.RecyclerView.getChildViewHolderInt(RecyclerView.java:4609)
        at android.support.v7.widget.RecyclerView.getChildAdapterPosition(RecyclerView.java:4628)
        at app.com.tvrecyclerview.TvRecyclerView.requestChildFocus(TvRecyclerView.java:314)
        at android.view.ViewGroup.requestChildFocus(ViewGroup.java:819)
        at android.view.ViewGroup.requestChildFocus(ViewGroup.java:819)
        at android.view.View.handleFocusGainInternal(View.java:6926)
        at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:795)
        at android.view.View.requestFocusNoSearch(View.java:11546)
        at android.view.View.requestFocus(View.java:11520)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3230)
        at android.view.ViewRootImpl$ViewPostImeInputStage.performFocusNavigation(ViewRootImpl.java:4976)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5093)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4779)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by henryblue** [comment]
thanks, you can try in 1.2.3 version

**Comment by green985** [comment]
Thanks but I test it and error still crash my app. 

I use 1.2.3 version. 

Thanks for support

**Comment by green985** [comment]
Thanks but I test it and error still crash my app. 

I try 1.2.3 version.

I use one more TvRecyclerview in one layout. When I try to navigate on list this exception will appear. 

Thanks for support

**Comment by henryblue** [comment]
Can you say something more specific? Or put a picture to describe
