### ISSUE TITLE
java.lang.NullPointerException（点击任何一个按钮界面就溃了）

### ISSUE THREAD

**Issue by todaywork** [henryblue/TvRecyclerView#41]
java.lang.NullPointerException
        at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:10000)
        at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:72)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat

**Comment by henryblue** [comment]
能否描述的清楚一些

**Comment by henryblue** [comment]
能否描述的清楚一些
